[package]
name = "mongodb-cursor-pagination"
version = "0.1.0"
authors = ["Brian DeBoer <bdeboer@noreply.com>"]
edition = "2018"
license = "MIT"
keywords = ["mongo", "mongodb", "database", "bson", "cursor", "pagination"]
readme = "README.md"
repository = "https://github.com/briandeboer/mongodb-cursor-pagination"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.11.0"
bson = "0.14.0"
log = "0.4.8"
mongodb = "0.9.0"
serde = "1.0"